myapplication/myapplication/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import include,path
from django.shortcuts import render

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls1')),
    path('post/',include('post.urls')),
]


myapplication/post/urls.py
from django.urls import path
from .import views

app_name = "post"

urlpatterns = [
    path('', views.index,name='index'),
    path('<int:question_id>/',views.detail,name='detail'),
    path('<int:question_id>/results/',views.results, name='results'),
    path('<int:question_id>/vote/',views.vote, name= 'vote'),

]

myapplication/post/models.py
from django.db import models

class  Question(models.Model):
    question_text = models.CharField(max_length =200)
    pub_date = models.DateTimeField('data published')

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    Choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


myapplication/post/views.py
from urllib import response
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question,Choice
from django.urls import reverse
from django.template import loader
from django.views import generic


# Create your views here.
def main(request):
     return render(request,"post/main.html")

# def detail(request, question_id):
#     return HttpResponse("you are looking at question %s" % question_id)

# def results(request, question_id):
#     response = "you are looking at the results of question %s"
#     return HttpResponse(response % question_id)

# def vote(request, question_id):
#     return HttpResponse("you are voting on question %s" % question_id)

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    #template = loader.get_template('post/index.html')
    context = {
        'latest_question_list' : latest_question_list}
    return render(request,'post/index.html',context)

# class IndexView(generic.ListView):
#     template_name: 'post/index.html'
#     context_object_name: 'latest_question_list'
#     def get_queryset(self):
#         return Question.objects.order_by('pub_date')[:5]

# class DetailView(generic.DetailView):
#     model: Question
#     template_name: 'post/detail.html'

# class ResultsView(generic.DetailView):
#     model: Question
#     template_name: 'post/results.html'

def detail(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'post/detail.html', {'question': question})

def vote(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request,'post/detail.html',{
            'question': question,
            'error_message': "you didn't select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('post:results', args=(question.id,)))

def results(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request,'post/results.html',{'question': question})

myapplication/post/templates/post/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<ul>    
    <form action="{% url 'post:vote' question.id %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.Choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
        </form>
</ul>
</body>
</html>

myapplication/post/templates/post/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    {% if latest_question_list %}
        <ol>
        {% for question in latest_question_list %}
            <li><a href="{% url 'post:detail' question.id%}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ol>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>
</html>

myapplication/post/templates/post/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <button><a href="/post/">
        GO to Post
    </a></button>
</body>
</html>

myapplication/post/templates/post/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.Choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'post:detail' question.id %}">Vote again?</a>
</body>
</html>